version: "3"
services:
  web:
    build: ./web
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/omamori-web/node_modules
      - ./web/src:/app/omamori-web/src
      - ./web/public:/app/omamori-web/public
    links:
      - server
  server:
    build: ./server
    restart: always
    ports:
      - "3443:3443"
    volumes:
      - /app/omamori-server/node_modules
      - ./server:/app/omamori-server
